### ISSUE TITLE
No releases on packagist

### ISSUE THREAD

**Issue by diversen** [Riimu/Kit-CSRF#3]
I was wondering if this is a packagist problem or if you releases has gone on packagist.org - before I could install a version, I think it was `2.4.0` - but now composer says it `Could not find package Riimu/Kit-CSRF`, and I can not see any releases of the package on packagist - I have also tested this from an empty dir, and then `composer require riimu/kit-csrf`.  But maybe there never has been a release on packagist, but only the `dev-master`?

**Comment by Riimu** [comment]
Thank you for reporting this to me. I have no idea how the releases disappeared from packagist. I have forced an update from packagist's side, which reloaded the release tags back into packagist. I have also created an [issue](https://github.com/composer/packagist/issues/610) in packagist repository (although with very little information).

But anyway, installing the package should now work as intended.
